name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        collection_id: 
          - "8ff5d78b-c9de-4590-bd82-1e64689d81cc"
          - "ada46968-73f0-4c27-ba1f-e5022ef1de1c"

    steps:

      - name: Instalar Postman CLI
        run: curl -o- https://dl-cli.pstmn.io/install/linux64.sh | sh

      - name: Autenticarse con Postman API
        run: postman login --with-api-key PMAK-67d3651b7dc2730001805eff-dfc938e9fff7540d831de3bec4259f0e63

      - name: Ejecutar pruebas con Postman CLI
        id: run_tests
        continue-on-error: true
        run: |
          for collection_id in "8ff5d78b-c9de-4590-bd82-1e64689d81cc" "ada46968-73f0-4c27-ba1f-e5022ef1de1c"; do
            postman collection run "$collection_id" \
              --environment 19150850-c63c8089-ea3f-4b19-ac50-57ace60da05a \
              --reporters junit \
              --reporter-junit-export "report-${collection_id}.xml"
          done
            
      - name: Publicar Reporte de Pruebas
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: "report-*.xml"
