name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Instalar Postman CLI
        run: |
          curl -o- https://dl-cli.pstmn.io/install/linux64.sh | sh

      - name: Autenticarse con Postman API
        run: postman login --with-api-key PMAK-67d3651b7dc2730001805eff-dfc938e9fff7540d831de3bec4259f0e63

      - name: Ejecutar pruebas con Postman CLI
        id: run_tests
        continue-on-error: true
        run: |
          postman collection run ada46968-73f0-4c27-ba1f-e5022ef1de1c \
            --environment-id 19150850-c63c8089-ea3f-4b19-ac50-57ace60da05a
